# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Midnightconman's Blog
description: >- 
  Trying to add description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://midnightconman.github.io/"
permalink: /blog/:year/:month/:day/:title/
github_username: midnightconman

# Build settings
markdown: kramdown
#theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

paginate: 10
paginate_path: "/blog/:num/"

recent_posts: 5
excerpt_link: "Read More"
titlecase: true
category_dir: blog/categories

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
