baseURL = 'https://midnightconman.github.io/'
languageCode = 'en-us'
title = "Midnightconman's Newsletter"
theme = "simpleness"

enableInlineShortcodes = true
enableEmoji = true

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2021"
  description = "A programming blog."
  disqus = "midnightconman"

[menu]
  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 1
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[social]
  github = "https://github.com/midnightconman"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  # doc: https://gohugo.io/getting-started/configuration-markup#highlight
  # syntax style: https://xyproto.github.io/splash/docs/longer/all.html
  [markup.highlight]
    guessSyntax = true
    hl_Lines = ""
    # lineNoStart = 1
    # lineNos = true
    # lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
